name: droidenv
channels:
  - defaults
dependencies:
  - nvidia::cudatoolkit=11.3.1
  - pytorch::pytorch=1.10.0
  - pytorch::torchvision=0.11.0
  - pytorch::torchaudio=0.10.0
  - rusty1s::pytorch-scatter
  - open3d-admin::open3d
  - tensorboard
  - scipy
  - tqdm
  - suitesparse
  - matplotlib
  - pyyaml
  - conda-forge::opencv
